# Generated by Django 2.1.2 on 2018-10-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0002_auto_20181029_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fechaNac',
        ),
    ]
