# Generated by Django 2.1.2 on 2018-10-30 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0003_remove_persona_fechanac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='region',
        ),
    ]
