# Generated by Django 2.1.2 on 2018-10-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0004_auto_20181029_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
    ]
