# Generated by Django 2.1.2 on 2018-10-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misPerris', '0005_remove_persona_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='rut',
        ),
    ]
